---

- hosts: listlocal
  gather_facts: true

  vars_files:
    - vars/main.yml

  roles:
    # - geerlingguy.firewall
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    # - geerlingguy.mysql
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.nginx
